sudo: false

language: php

matrix:
  include:
    - php: 7.1
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: SYMFONY_VERSION=2.7.*
    - php: 7.2
      env: SYMFONY_VERSION=2.8.*
    - php: 7.2
      env: SYMFONY_VERSION=3.3.*
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*
    - php: 7.2
      env: SYMFONY_VERSION=4.0.*
    - php: 7.2
      env: SYMFONY_VERSION=4.0.* REQUIRE_PROXY_BRIDGE="" EXTRA_PHPUNIT_PARAMS="--group depTest"

env:
  global:
    - SYMFONY_VERSION=""
    - REQUIRE_PROXY_BRIDGE="yes"
    - EXTRA_PHPUNIT_PARAMS="--exclude-group depTest"
    - COMPOSER_FLAGS="--prefer-dist"

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/config:$SYMFONY_VERSION symfony/console:$SYMFONY_VERSION symfony/dependency-injection:$SYMFONY_VERSION symfony/finder:$SYMFONY_VERSION symfony/framework-bundle:$SYMFONY_VERSION symfony/http-kernel:$SYMFONY_VERSION symfony/monolog-bridge:$SYMFONY_VERSION symfony/process:$SYMFONY_VERSION symfony/yaml:$SYMFONY_VERSION ; fi

install:
  - composer update $COMPOSER_FLAGS
  - if [ "$REQUIRE_PROXY_BRIDGE" == "yes" ] && [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/proxy-manager-bridge:$SYMFONY_VERSION; fi
  - if [ "$REQUIRE_PROXY_BRIDGE" == "yes" ] && [ "$SYMFONY_VERSION" == "" ]; then composer require symfony/proxy-manager-bridge; fi

script:
  - ./vendor/bin/phpunit $EXTRA_PHPUNIT_PARAMS
