sudo: false

language: php

matrix:
  include:
    - php: 7.1
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: SYMFONY_VERSION=2.7.*
    - php: 7.2
      env: SYMFONY_VERSION=2.8.*
    - php: 7.2
      env: SYMFONY_VERSION=3.2.*
    - php: 7.2
      env: SYMFONY_VERSION=3.3.*

env:
  global:
    - SYMFONY_VERSION=""
    - COMPOSER_FLAGS="--prefer-dist"

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/console:$SYMFONY_VERSION symfony/process:$SYMFONY_VERSION symfony/finder:$SYMFONY_VERSION; fi

install:
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit

