sudo: false

language: php

services:
  - rabbitmq

matrix:
  include:
    - php: 7.2
      env: SYMFONY_VERSION=2.7.*
    - php: 7.2
      env: SYMFONY_VERSION=2.8.*
    - php: 7.2
      env: SYMFONY_VERSION=3.3.*
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*
    - php: 7.2
      env: SYMFONY_VERSION=4.0.*

env:
  global:
    - SYMFONY_VERSION=""

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/console:$SYMFONY_VERSION symfony/finder:$SYMFONY_VERSION symfony/process:$SYMFONY_VERSION symfony/translation:$SYMFONY_VERSION; fi

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit

